### ISSUE TITLE
Does not work on 1.15

### ISSUE THREAD

**Issue by tererun** [Maximvdw/ArcadeBoard-API#7]
I added PlaceholderAPI, MVdWPlaceholderAPI, and MVdWUpdater, but an error occurred when loading, and when I entered the command, it returned "/ arcadeboard (Startup errpr! PM Maximvdw with the startup log and proof of purchase)".

`[10:38:08] [Server thread/INFO]: [ArcadeBoard] Enabling ArcadeBoard v1.3.0
[10:38:08] [Server thread/WARN]: [AutoSaveWorld] Loaded class be.arcadeboard.cg from ArcadeBoard v1.3.0 which is not a depend, softdepend or loadbefore of this plugin.
[10:38:08] [Server thread/WARN]: [AutoSaveWorld] Plugin ArcadeBoard attempted to establish connection https://api.spigotmc.org/legacy/premium.php?user_id=498228&resource_id=64836once=1841230220 in main server thread
[10:38:08] [Server thread/WARN]: [AutoSaveWorld] Plugin ArcadeBoard attempted to establish connection socket://api.spigotmc.org:443 in main server thread
[10:38:08] [Server thread/INFO]: [ArcadeBoard] -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Plugin: ArcadeBoard v1.3.0
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Framework version: 2019-05
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Author: Maximvdw (Maxim Van de Wynckel)
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Site: https://www.mvdw-software.com/
[10:38:08] [Server thread/INFO]: [ArcadeBoard] -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Loading database driver ...
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Downloading Javax Persistence 2.1.0 ...
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Description: Used to database mapping
[10:38:08] [Server thread/WARN]: [AutoSaveWorld] Plugin ArcadeBoard attempted to establish connection http://central.maven.org/maven2/org/eclipse/persistence/javax.persistence/2.1.0/javax.persistence-2.1.0.jar in main server thread
[10:38:08] [Server thread/WARN]: [AutoSaveWorld] Plugin ArcadeBoard attempted to establish connection socket://central.maven.org:80 in main server thread
[10:38:08] [Server thread/ERROR]: [ArcadeBoard] An error occured while downloading a required lib.
[10:38:08] [Server thread/WARN]: java.net.UnknownHostException: central.maven.org
[10:38:08] [Server thread/WARN]:        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
[10:38:08] [Server thread/WARN]:        at java.net.PlainSocketImpl.connect(Unknown Source)
[10:38:08] [Server thread/WARN]:        at java.net.SocksSocketImpl.connect(Unknown Source)
[10:38:08] [Server thread/WARN]:        at java.net.Socket.connect(Unknown Source)
[10:38:08] [Server thread/WARN]:        at java.net.Socket.connect(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.NetworkClient.doConnect(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.http.HttpClient.openServer(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.http.HttpClient.openServer(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.http.HttpClient.<init>(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.http.HttpClient.New(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.http.HttpClient.New(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[10:38:08] [Server thread/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[10:38:08] [Server thread/WARN]:        at be.arcadeboard.dk.a(dk.java:6)
[10:38:08] [Server thread/WARN]:        at be.arcadeboard.cp.a(cp.java:12)
[10:38:08] [Server thread/WARN]:        at be.arcadeboard.cp.a(cp.java:24)
[10:38:08] [Server thread/WARN]:        at be.arcadeboard.cL.b(cL.java:4)
[10:38:08] [Server thread/WARN]:        at be.arcadeboard.cg.i(cg.java:13)
[10:38:08] [Server thread/WARN]:        at be.arcadeboard.cg.onEnable(cg.java:54)
[10:38:08] [Server thread/WARN]:        at be.arcadeboard.cL.onEnable(cL.java:39)
[10:38:08] [Server thread/WARN]:        at be.arcadeboard.ArcadeBoard.onEnable(ArcadeBoard.java:36)
[10:38:08] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:38:08] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[10:38:08] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[10:38:08] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
[10:38:08] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
[10:38:08] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[10:38:08] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
[10:38:08] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[10:38:08] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[10:38:08] [Server thread/WARN]: [ArcadeBoard] The plugin was unable to download the required dependencies!
[10:38:08] [Server thread/WARN]: [ArcadeBoard] Make sure you are using a compatible Java version and have internet connection.
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Loading configuration ...
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Loading messages ...
[10:38:08] [Server thread/INFO]: [ArcadeBoard] Loading language file: lang_en
[10:38:09] [Server thread/INFO]: [ArcadeBoard] Using ActionTextv4 core
[10:38:09] [Server thread/ERROR]: Error occurred while enabling ArcadeBoard v1.3.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/j256/ormlite/support/ConnectionSource
        at be.arcadeboard.cL.l(cL.java:35) ~[?:?]
        at be.arcadeboard.ArcadeBoard.l(ArcadeBoard.java:14) ~[?:?]
        at be.arcadeboard.cg.i(cg.java:31) ~[?:?]
        at be.arcadeboard.cg.onEnable(cg.java:54) ~[?:?]
        at be.arcadeboard.cL.onEnable(cL.java:39) ~[?:?]
        at be.arcadeboard.ArcadeBoard.onEnable(ArcadeBoard.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: com.j256.ormlite.support.ConnectionSource
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        ... 15 more`

This is the console log.

`02/04/2020 10:38:08 [INFO] Loading messages ...
02/04/2020 10:38:09 [DEBUG] Using SCOREBOARD v16
02/04/2020 10:38:08 [INFO] Loading language file: lang_en
02/04/2020 10:38:09 [INFO] Using ActionTextv4 core
`

This is the log in ArcadeBoard.

I'm Japanese and use Google Translate.
It may be difficult to understand, but please forgive me.

**Comment by tererun** [comment]
![image](https://user-images.githubusercontent.com/27857171/78208607-c03d6700-74df-11ea-84ce-09cf4161e0b0.png)

Of course I have purchased it.

**Comment by Maximvdw** [comment]
Hi,

I am investigating it

**Comment by tererun** [comment]
Okay
