### ISSUE TITLE
Error occurred while enabling ArcadeBoard v1.4.1 (Is it up to date?) Version 1.15.2

### ISSUE THREAD

**Issue by FuntasiaIT** [Maximvdw/ArcadeBoard-API#8]
java.lang.ExceptionInInitializerError: null
at be.arcadeboard.cl.m(cl.java:32) ~[?:?]
at be.arcadeboard.ArcadeBoard.m(ArcadeBoard.java:54) ~[?:?]
at be.arcadeboard.cY.g(cY.java:60) ~[?:?]
at be.arcadeboard.cY.onEnable(cY.java:65) ~[?:?]
at be.arcadeboard.cl.onEnable(cl.java:5) ~[?:?]
at be.arcadeboard.ArcadeBoard.onEnable(ArcadeBoard.java:52) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-162]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IllegalStateException: Unable to find method null ([class net.minecraft.server.v1_15_R1.ServerConnection]).
at be.arcadeboard.bm.a(bm.java:45) ~[?:?]
at be.arcadeboard.bm.a(bm.java:16) ~[?:?]
at be.arcadeboard.bm.a(bm.java:30) ~[?:?]
at be.arcadeboard.aB.<clinit>(aB.java:46) ~[?:?]
... 15 more

**Comment by sannielollie** [comment]
Seems like i am having the same issue. https://pastebin.com/Qtj2reZB

**Comment by sannielollie** [comment]
Still not solved in latest version (wich even includes 1.16 update) is the author ignoring this?

**Comment by sannielollie** [comment]
Also the latest version is still not working: https://pastebin.com/ii05NRMC
